export type LaunchFeatureStatus = "implemented" | "in_progress" | "planned"
export type LaunchFeaturePriority = "P0" | "P1" | "P2"

export type LaunchFeatureItem = {
  id: string
  category: string
  title: string
  required: true
  status: LaunchFeatureStatus
  priority: LaunchFeaturePriority
  owner: "platform" | "content" | "growth" | "security"
  phase: "foundation" | "beta" | "scale"
  dependsOn?: string[]
}

export const launchFeatureCatalog: LaunchFeatureItem[] = [
  { id: "F001", category: "Authentication & Identity", title: "Email/password sign-up", required: true, status: "implemented", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F002", category: "Authentication & Identity", title: "Google OAuth sign-in", required: true, status: "implemented", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F003", category: "Authentication & Identity", title: "Email verification", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F004", category: "Authentication & Identity", title: "Password reset", required: true, status: "implemented", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F005", category: "Authentication & Identity", title: "Session management", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation", dependsOn: ['F004'] },
  { id: "F006", category: "Authentication & Identity", title: "Multi-device sessions", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F007", category: "Authentication & Identity", title: "Role bootstrap", required: true, status: "implemented", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F008", category: "Authentication & Identity", title: "Onboarding wizard", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F009", category: "Authentication & Identity", title: "Public student ID", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F010", category: "Authentication & Identity", title: "QR profile sharing", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta", dependsOn: ['F009'] },
  { id: "F011", category: "Authentication & Identity", title: "Admin 2FA", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F012", category: "Authentication & Identity", title: "Brute-force lockout", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F013", category: "Authentication & Identity", title: "Suspicious login alerts", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F014", category: "Authentication & Identity", title: "Profile completion score", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F015", category: "Authentication & Identity", title: "Account soft-delete", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale", dependsOn: ['F014'] },
  { id: "F016", category: "Authentication & Identity", title: "Account restore window", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F017", category: "Authentication & Identity", title: "Username policy", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F018", category: "Authentication & Identity", title: "Device trust settings", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F019", category: "Authentication & Identity", title: "Security questions fallback", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F020", category: "Authentication & Identity", title: "Session activity log", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale", dependsOn: ['F019'] },
  { id: "F021", category: "Courses & Content", title: "Course draft/publish", required: true, status: "planned", priority: "P0", owner: "content", phase: "foundation" },
  { id: "F022", category: "Courses & Content", title: "Course sections builder", required: true, status: "planned", priority: "P0", owner: "content", phase: "foundation" },
  { id: "F023", category: "Courses & Content", title: "Lesson ordering", required: true, status: "planned", priority: "P0", owner: "content", phase: "foundation" },
  { id: "F024", category: "Courses & Content", title: "Rich text lesson editor", required: true, status: "planned", priority: "P0", owner: "content", phase: "foundation" },
  { id: "F025", category: "Courses & Content", title: "Video upload", required: true, status: "planned", priority: "P0", owner: "content", phase: "foundation", dependsOn: ['F024'] },
  { id: "F026", category: "Courses & Content", title: "Lesson attachments", required: true, status: "planned", priority: "P0", owner: "content", phase: "foundation" },
  { id: "F027", category: "Courses & Content", title: "Lesson prerequisites", required: true, status: "planned", priority: "P0", owner: "content", phase: "foundation" },
  { id: "F028", category: "Courses & Content", title: "Course visibility rules", required: true, status: "planned", priority: "P1", owner: "content", phase: "beta" },
  { id: "F029", category: "Courses & Content", title: "Enrollment limits", required: true, status: "planned", priority: "P1", owner: "content", phase: "beta" },
  { id: "F030", category: "Courses & Content", title: "Completion certificates", required: true, status: "planned", priority: "P1", owner: "content", phase: "beta", dependsOn: ['F029'] },
  { id: "F031", category: "Courses & Content", title: "Lesson progress sync", required: true, status: "in_progress", priority: "P1", owner: "content", phase: "beta" },
  { id: "F032", category: "Courses & Content", title: "Resume playback", required: true, status: "planned", priority: "P1", owner: "content", phase: "beta" },
  { id: "F033", category: "Courses & Content", title: "Learning streak", required: true, status: "planned", priority: "P1", owner: "content", phase: "beta" },
  { id: "F034", category: "Courses & Content", title: "Daily goal settings", required: true, status: "planned", priority: "P1", owner: "content", phase: "beta" },
  { id: "F035", category: "Courses & Content", title: "Course analytics", required: true, status: "in_progress", priority: "P2", owner: "content", phase: "scale", dependsOn: ['F034'] },
  { id: "F036", category: "Courses & Content", title: "Course tags", required: true, status: "planned", priority: "P2", owner: "content", phase: "scale" },
  { id: "F037", category: "Courses & Content", title: "Course SEO metadata", required: true, status: "planned", priority: "P2", owner: "content", phase: "scale" },
  { id: "F038", category: "Courses & Content", title: "Localization per course", required: true, status: "planned", priority: "P2", owner: "content", phase: "scale" },
  { id: "F039", category: "Courses & Content", title: "Content version history", required: true, status: "planned", priority: "P2", owner: "content", phase: "scale" },
  { id: "F040", category: "Courses & Content", title: "Archive/restore course", required: true, status: "planned", priority: "P2", owner: "content", phase: "scale", dependsOn: ['F039'] },
  { id: "F041", category: "Assessments & Exams", title: "Quiz creation UI", required: true, status: "in_progress", priority: "P0", owner: "content", phase: "foundation" },
  { id: "F042", category: "Assessments & Exams", title: "Question bank", required: true, status: "planned", priority: "P0", owner: "content", phase: "foundation" },
  { id: "F043", category: "Assessments & Exams", title: "MCQ support", required: true, status: "planned", priority: "P0", owner: "content", phase: "foundation" },
  { id: "F044", category: "Assessments & Exams", title: "True/false support", required: true, status: "planned", priority: "P0", owner: "content", phase: "foundation" },
  { id: "F045", category: "Assessments & Exams", title: "Image question media", required: true, status: "planned", priority: "P0", owner: "content", phase: "foundation", dependsOn: ['F044'] },
  { id: "F046", category: "Assessments & Exams", title: "Video question media", required: true, status: "planned", priority: "P0", owner: "content", phase: "foundation" },
  { id: "F047", category: "Assessments & Exams", title: "Timed attempts", required: true, status: "planned", priority: "P0", owner: "content", phase: "foundation" },
  { id: "F048", category: "Assessments & Exams", title: "Attempt limits", required: true, status: "planned", priority: "P1", owner: "content", phase: "beta" },
  { id: "F049", category: "Assessments & Exams", title: "Per-question explanation", required: true, status: "planned", priority: "P1", owner: "content", phase: "beta" },
  { id: "F050", category: "Assessments & Exams", title: "Auto grading", required: true, status: "planned", priority: "P1", owner: "content", phase: "beta", dependsOn: ['F049'] },
  { id: "F051", category: "Assessments & Exams", title: "Manual override grading", required: true, status: "planned", priority: "P1", owner: "content", phase: "beta" },
  { id: "F052", category: "Assessments & Exams", title: "Skill-wise breakdown", required: true, status: "planned", priority: "P1", owner: "content", phase: "beta" },
  { id: "F053", category: "Assessments & Exams", title: "Anti-cheat fullscreen", required: true, status: "planned", priority: "P1", owner: "content", phase: "beta" },
  { id: "F054", category: "Assessments & Exams", title: "Randomized order", required: true, status: "planned", priority: "P1", owner: "content", phase: "beta" },
  { id: "F055", category: "Assessments & Exams", title: "Question tags", required: true, status: "planned", priority: "P2", owner: "content", phase: "scale", dependsOn: ['F054'] },
  { id: "F056", category: "Assessments & Exams", title: "Negative marking", required: true, status: "planned", priority: "P2", owner: "content", phase: "scale" },
  { id: "F057", category: "Assessments & Exams", title: "Sectional scoring", required: true, status: "planned", priority: "P2", owner: "content", phase: "scale" },
  { id: "F058", category: "Assessments & Exams", title: "Question import CSV", required: true, status: "planned", priority: "P2", owner: "content", phase: "scale" },
  { id: "F059", category: "Assessments & Exams", title: "Exam proctoring hooks", required: true, status: "planned", priority: "P2", owner: "content", phase: "scale" },
  { id: "F060", category: "Assessments & Exams", title: "Retake policy rules", required: true, status: "planned", priority: "P2", owner: "content", phase: "scale", dependsOn: ['F059'] },
  { id: "F061", category: "Payments & Offers", title: "Checkout flow", required: true, status: "implemented", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F062", category: "Payments & Offers", title: "Coupon validation", required: true, status: "implemented", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F063", category: "Payments & Offers", title: "Percent coupons", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F064", category: "Payments & Offers", title: "Fixed coupons", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F065", category: "Payments & Offers", title: "Free-course coupons", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation", dependsOn: ['F064'] },
  { id: "F066", category: "Payments & Offers", title: "Usage limits", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F067", category: "Payments & Offers", title: "Coupon expiry", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F068", category: "Payments & Offers", title: "Offer details page", required: true, status: "in_progress", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F069", category: "Payments & Offers", title: "Offer schedule", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F070", category: "Payments & Offers", title: "Payment receipt", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta", dependsOn: ['F069'] },
  { id: "F071", category: "Payments & Offers", title: "Payment retry", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F072", category: "Payments & Offers", title: "Billing history", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F073", category: "Payments & Offers", title: "Refund requests", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F074", category: "Payments & Offers", title: "Instructor campaigns", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F075", category: "Payments & Offers", title: "Currency localization", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale", dependsOn: ['F074'] },
  { id: "F076", category: "Payments & Offers", title: "Invoice PDF export", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F077", category: "Payments & Offers", title: "Tax calculation", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F078", category: "Payments & Offers", title: "Subscription upgrades", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F079", category: "Payments & Offers", title: "Dunning reminders", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F080", category: "Payments & Offers", title: "Fraud risk checks", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale", dependsOn: ['F079'] },
  { id: "F081", category: "Messaging & Community", title: "Direct messaging", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F082", category: "Messaging & Community", title: "Teacher broadcasts", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F083", category: "Messaging & Community", title: "Disable broadcast replies", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F084", category: "Messaging & Community", title: "Conversation mute", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F085", category: "Messaging & Community", title: "Unread sync", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation", dependsOn: ['F084'] },
  { id: "F086", category: "Messaging & Community", title: "Message attachments", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F087", category: "Messaging & Community", title: "Message search", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F088", category: "Messaging & Community", title: "Typing indicators", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F089", category: "Messaging & Community", title: "Read receipts", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F090", category: "Messaging & Community", title: "User blocking", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta", dependsOn: ['F089'] },
  { id: "F091", category: "Messaging & Community", title: "Conversation reporting", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F092", category: "Messaging & Community", title: "Moderation queue", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F093", category: "Messaging & Community", title: "Group channels", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F094", category: "Messaging & Community", title: "Pinned posts", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F095", category: "Messaging & Community", title: "Threaded replies", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale", dependsOn: ['F094'] },
  { id: "F096", category: "Messaging & Community", title: "Mention notifications", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F097", category: "Messaging & Community", title: "Message reactions", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F098", category: "Messaging & Community", title: "Voice notes", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F099", category: "Messaging & Community", title: "Chat retention policy", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F100", category: "Messaging & Community", title: "Community guidelines prompts", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale", dependsOn: ['F099'] },
  { id: "F101", category: "Notifications & Engagement", title: "In-app notifications", required: true, status: "implemented", priority: "P0", owner: "growth", phase: "foundation" },
  { id: "F102", category: "Notifications & Engagement", title: "Mark all read", required: true, status: "implemented", priority: "P0", owner: "growth", phase: "foundation" },
  { id: "F103", category: "Notifications & Engagement", title: "Course update alerts", required: true, status: "planned", priority: "P0", owner: "growth", phase: "foundation" },
  { id: "F104", category: "Notifications & Engagement", title: "Quiz reminders", required: true, status: "planned", priority: "P0", owner: "growth", phase: "foundation" },
  { id: "F105", category: "Notifications & Engagement", title: "Live session reminders", required: true, status: "planned", priority: "P0", owner: "growth", phase: "foundation", dependsOn: ['F104'] },
  { id: "F106", category: "Notifications & Engagement", title: "Offer targeting", required: true, status: "planned", priority: "P0", owner: "growth", phase: "foundation" },
  { id: "F107", category: "Notifications & Engagement", title: "Weekly digest", required: true, status: "planned", priority: "P0", owner: "growth", phase: "foundation" },
  { id: "F108", category: "Notifications & Engagement", title: "Achievement alerts", required: true, status: "planned", priority: "P1", owner: "growth", phase: "beta" },
  { id: "F109", category: "Notifications & Engagement", title: "Preference controls", required: true, status: "in_progress", priority: "P1", owner: "growth", phase: "beta" },
  { id: "F110", category: "Notifications & Engagement", title: "Deep-link routing", required: true, status: "planned", priority: "P1", owner: "growth", phase: "beta", dependsOn: ['F109'] },
  { id: "F111", category: "Notifications & Engagement", title: "Push notifications", required: true, status: "planned", priority: "P1", owner: "growth", phase: "beta" },
  { id: "F112", category: "Notifications & Engagement", title: "Email templates", required: true, status: "planned", priority: "P1", owner: "growth", phase: "beta" },
  { id: "F113", category: "Notifications & Engagement", title: "SMS fallback", required: true, status: "planned", priority: "P1", owner: "growth", phase: "beta" },
  { id: "F114", category: "Notifications & Engagement", title: "Quiet hours", required: true, status: "planned", priority: "P1", owner: "growth", phase: "beta" },
  { id: "F115", category: "Notifications & Engagement", title: "Timezone-aware scheduling", required: true, status: "planned", priority: "P2", owner: "growth", phase: "scale", dependsOn: ['F114'] },
  { id: "F116", category: "Notifications & Engagement", title: "Digest personalization", required: true, status: "planned", priority: "P2", owner: "growth", phase: "scale" },
  { id: "F117", category: "Notifications & Engagement", title: "Notification A/B tests", required: true, status: "planned", priority: "P2", owner: "growth", phase: "scale" },
  { id: "F118", category: "Notifications & Engagement", title: "Notification delivery metrics", required: true, status: "planned", priority: "P2", owner: "growth", phase: "scale" },
  { id: "F119", category: "Notifications & Engagement", title: "Reminder snooze", required: true, status: "planned", priority: "P2", owner: "growth", phase: "scale" },
  { id: "F120", category: "Notifications & Engagement", title: "Engagement score", required: true, status: "planned", priority: "P2", owner: "growth", phase: "scale", dependsOn: ['F119'] },
  { id: "F121", category: "Admin & Instructor Operations", title: "Admin dashboard", required: true, status: "implemented", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F122", category: "Admin & Instructor Operations", title: "Instructor analytics", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F123", category: "Admin & Instructor Operations", title: "Progress exports", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F124", category: "Admin & Instructor Operations", title: "Content moderation", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F125", category: "Admin & Instructor Operations", title: "Report triage", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation", dependsOn: ['F124'] },
  { id: "F126", category: "Admin & Instructor Operations", title: "Role management", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F127", category: "Admin & Instructor Operations", title: "Audit logs", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F128", category: "Admin & Instructor Operations", title: "Feature flags", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F129", category: "Admin & Instructor Operations", title: "Content takedown", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F130", category: "Admin & Instructor Operations", title: "Bulk announcements", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta", dependsOn: ['F129'] },
  { id: "F131", category: "Admin & Instructor Operations", title: "Teacher payout reports", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F132", category: "Admin & Instructor Operations", title: "Dispute management", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F133", category: "Admin & Instructor Operations", title: "Policy violation workflow", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F134", category: "Admin & Instructor Operations", title: "Academic integrity dashboard", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F135", category: "Admin & Instructor Operations", title: "Staff permissions matrix", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale", dependsOn: ['F134'] },
  { id: "F136", category: "Admin & Instructor Operations", title: "Campus/organization support", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F137", category: "Admin & Instructor Operations", title: "Impersonation audit mode", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F138", category: "Admin & Instructor Operations", title: "Workflow automation rules", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F139", category: "Admin & Instructor Operations", title: "Operational SLA board", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F140", category: "Admin & Instructor Operations", title: "Admin notes on users", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale", dependsOn: ['F139'] },
  { id: "F141", category: "Security & Compliance", title: "Health endpoint", required: true, status: "implemented", priority: "P0", owner: "security", phase: "foundation" },
  { id: "F142", category: "Security & Compliance", title: "Error code normalization", required: true, status: "implemented", priority: "P0", owner: "security", phase: "foundation" },
  { id: "F143", category: "Security & Compliance", title: "RLS coverage", required: true, status: "in_progress", priority: "P0", owner: "security", phase: "foundation" },
  { id: "F144", category: "Security & Compliance", title: "Server auth guard", required: true, status: "implemented", priority: "P0", owner: "security", phase: "foundation" },
  { id: "F145", category: "Security & Compliance", title: "Admin route guard", required: true, status: "implemented", priority: "P0", owner: "security", phase: "foundation", dependsOn: ['F144'] },
  { id: "F146", category: "Security & Compliance", title: "Rate limiting", required: true, status: "planned", priority: "P0", owner: "security", phase: "foundation" },
  { id: "F147", category: "Security & Compliance", title: "CSRF protection", required: true, status: "planned", priority: "P0", owner: "security", phase: "foundation" },
  { id: "F148", category: "Security & Compliance", title: "XSS hardening", required: true, status: "planned", priority: "P1", owner: "security", phase: "beta" },
  { id: "F149", category: "Security & Compliance", title: "Dependency scanning", required: true, status: "planned", priority: "P1", owner: "security", phase: "beta" },
  { id: "F150", category: "Security & Compliance", title: "Secret scanning", required: true, status: "planned", priority: "P1", owner: "security", phase: "beta", dependsOn: ['F149'] },
  { id: "F151", category: "Security & Compliance", title: "Automated backups", required: true, status: "planned", priority: "P1", owner: "security", phase: "beta" },
  { id: "F152", category: "Security & Compliance", title: "Disaster recovery runbook", required: true, status: "planned", priority: "P1", owner: "security", phase: "beta" },
  { id: "F153", category: "Security & Compliance", title: "Sentry monitoring", required: true, status: "planned", priority: "P1", owner: "security", phase: "beta" },
  { id: "F154", category: "Security & Compliance", title: "Structured logging", required: true, status: "planned", priority: "P1", owner: "security", phase: "beta" },
  { id: "F155", category: "Security & Compliance", title: "Performance alerts", required: true, status: "planned", priority: "P2", owner: "security", phase: "scale", dependsOn: ['F154'] },
  { id: "F156", category: "Security & Compliance", title: "Data retention policy", required: true, status: "planned", priority: "P2", owner: "security", phase: "scale" },
  { id: "F157", category: "Security & Compliance", title: "GDPR delete requests", required: true, status: "planned", priority: "P2", owner: "security", phase: "scale" },
  { id: "F158", category: "Security & Compliance", title: "PII encryption-at-rest", required: true, status: "planned", priority: "P2", owner: "security", phase: "scale" },
  { id: "F159", category: "Security & Compliance", title: "Security headers policy", required: true, status: "planned", priority: "P2", owner: "security", phase: "scale" },
  { id: "F160", category: "Security & Compliance", title: "Pen-test checklist", required: true, status: "planned", priority: "P2", owner: "security", phase: "scale", dependsOn: ['F159'] },
  { id: "F161", category: "Platform Reliability & DevEx", title: "CI lint checks", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F162", category: "Platform Reliability & DevEx", title: "CI build checks", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F163", category: "Platform Reliability & DevEx", title: "Unit test suite", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F164", category: "Platform Reliability & DevEx", title: "Integration tests", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F165", category: "Platform Reliability & DevEx", title: "E2E smoke tests", required: true, status: "in_progress", priority: "P0", owner: "platform", phase: "foundation", dependsOn: ['F164'] },
  { id: "F166", category: "Platform Reliability & DevEx", title: "Regression checklist", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F167", category: "Platform Reliability & DevEx", title: "Release checklist", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F168", category: "Platform Reliability & DevEx", title: "Canary deployments", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F169", category: "Platform Reliability & DevEx", title: "Rollback automation", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F170", category: "Platform Reliability & DevEx", title: "DB migration rollback", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta", dependsOn: ['F169'] },
  { id: "F171", category: "Platform Reliability & DevEx", title: "Schema drift detection", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F172", category: "Platform Reliability & DevEx", title: "API contract testing", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F173", category: "Platform Reliability & DevEx", title: "Synthetic monitoring", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F174", category: "Platform Reliability & DevEx", title: "Uptime dashboard", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F175", category: "Platform Reliability & DevEx", title: "Incident response playbook", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale", dependsOn: ['F174'] },
  { id: "F176", category: "Platform Reliability & DevEx", title: "On-call rotation docs", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F177", category: "Platform Reliability & DevEx", title: "Error budget tracking", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F178", category: "Platform Reliability & DevEx", title: "Performance budgets", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F179", category: "Platform Reliability & DevEx", title: "Cache invalidation strategy", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F180", category: "Platform Reliability & DevEx", title: "Queue retry policy", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale", dependsOn: ['F179'] },
  { id: "F181", category: "UX, Accessibility & Intelligence", title: "Sidebar labels", required: true, status: "implemented", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F182", category: "UX, Accessibility & Intelligence", title: "Keyboard navigation", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F183", category: "UX, Accessibility & Intelligence", title: "Aria labels", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F184", category: "UX, Accessibility & Intelligence", title: "Empty states", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F185", category: "UX, Accessibility & Intelligence", title: "Loading skeletons", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation", dependsOn: ['F184'] },
  { id: "F186", category: "UX, Accessibility & Intelligence", title: "Form validation copy", required: true, status: "planned", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F187", category: "UX, Accessibility & Intelligence", title: "No dead links", required: true, status: "implemented", priority: "P0", owner: "platform", phase: "foundation" },
  { id: "F188", category: "UX, Accessibility & Intelligence", title: "Terms page", required: true, status: "implemented", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F189", category: "UX, Accessibility & Intelligence", title: "Privacy page", required: true, status: "implemented", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F190", category: "UX, Accessibility & Intelligence", title: "Responsive admin UI", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta", dependsOn: ['F189'] },
  { id: "F191", category: "UX, Accessibility & Intelligence", title: "Color contrast audit", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F192", category: "UX, Accessibility & Intelligence", title: "Localization readiness", required: true, status: "planned", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F193", category: "UX, Accessibility & Intelligence", title: "Smart search relevance", required: true, status: "in_progress", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F194", category: "UX, Accessibility & Intelligence", title: "Personalized recommendations", required: true, status: "in_progress", priority: "P1", owner: "platform", phase: "beta" },
  { id: "F195", category: "UX, Accessibility & Intelligence", title: "AI tutor context memory", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale", dependsOn: ['F194'] },
  { id: "F196", category: "UX, Accessibility & Intelligence", title: "Adaptive difficulty engine", required: true, status: "in_progress", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F197", category: "UX, Accessibility & Intelligence", title: "Learning path generator", required: true, status: "in_progress", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F198", category: "UX, Accessibility & Intelligence", title: "Accessibility screen-reader mode", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F199", category: "UX, Accessibility & Intelligence", title: "User intent analytics", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale" },
  { id: "F200", category: "UX, Accessibility & Intelligence", title: "Churn prediction insights", required: true, status: "planned", priority: "P2", owner: "platform", phase: "scale", dependsOn: ['F199'] },
]
